[project]
name = "IrenesBot"
version = "0.7.7"
description = "Personal Twitch.tv Bot"
readme = "README.md"
requires-python = ">=3.14"
authors = [{ name = "Aluerie", email = "aluerie@gmail.com" }]
maintainers = [{ name = "Aluerie", email = "aluerie@gmail.com" }]
urls.Homepage = "https://github.com/Aluerie/IrenesBot"
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Programming Language :: Python ",
    "Topic :: Twitch Bots",
    "Topic :: Utilities",
    "Typing :: Typed",
]
dependencies = [
    "aiofiles",
    "asyncpg",
    "backoff",
    "click",
    "discord-py[speed]",
    "orjson",
    "pydantic-settings",
    "pygit2",
    "steamio",
    "twitchio[starlette]",
    "uvloop ; sys_platform == 'linux'",
    "websockets",
    "zstandard",
]

[tool.uv.sources]
twitchio = { git = "https://github.com/PythonistaGuild/TwitchIO.git", rev = "main" }
steamio = { git = "https://github.com/Aluerie/steam.py", rev = "introduce-ext.dota2" }
stv-event-api = { git = "https://github.com/Aluerie/stv_event_api", rev = "master" }

[dependency-groups]
dev = [{ include-group = "type_lint" }, { include-group = "test" }, "prek"]
type_lint = ["asyncpg-stubs", "ruff", "ty"]
test = ["pytest", "pytest-asyncio"]
docs = [
    "numpydoc",
    "shibuya",
    "sphinx",
    "sphinx-copybutton",
    "sphinx-design",
    "sphinx-iconify",
]

[project.optional-dependencies]
tools = ["ipykernel"]

[[tool.uv.index]]
name = "umbra"
url = "https://about.abstractumbra.dev/pip/"
explicit = true

[tool.uv]
package = false


[tool.ty.rules]
all = "error"
dynamic-function-decorator-return = "ignore" # TwitchIO's decorators return `Any`
possibly-missing-import = "ignore" # False positives, maybe we'll try it later.
unsound-assignment = "ignore" # `Any` is fine
unsound-return-statement = "ignore" # `Any` is fine
unsound-yield = "ignore" # `Any` is fine


[tool.ruff]
preview = true
line-length = 125
target-version = "py314"
exclude = [".venv"]
src = ["src"]

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    # Recommended to disable by https://docs.astral.sh/ruff/formatter/#conflicting-lint-rules
    "tab-indentation",
    "indentation-with-invalid-multiple",
    "indentation-with-invalid-multiple-comment",
    "over-indented",
    "incorrect-blank-line-before-class",
    "docstring-tab-indentation",
    "triple-single-quotes",
    "bad-quotes-inline-string",
    "bad-quotes-multiline-string",
    "bad-quotes-docstring",
    "avoidable-escaped-quote",
    "unnecessary-escaped-quote",
    "missing-trailing-comma",
    "prohibited-trailing-comma",
    "multi-line-implicit-string-concatenation",
    # Docstring related
    "docstring-missing-exception", 
    "docstring-missing-returns",
    "docstring-missing-yields",
    "undocumented-magic-method",
    # Complexity memes
    "complex-structure",
    "too-many-arguments",
    "too-many-branches",
    "too-many-public-methods",
    "too-many-return-statements",
    "too-many-statements-in-try-clause",
    # Todo
    "line-contains-todo", # I use TODO Tree VSCode extension for this
    "missing-todo-author",
    "missing-todo-link",
    # Other (uncategorized) Rules
    "ambiguous-unicode-character-string",
    "any-type",
    "assert", # assert is fine for "casting" type checks and in tests
    "commented-out-code",
    "implicit-namespace-package", # Annoying rule, it doesn't know what **I** want to be an implicit namespace-package
    "magic-value-comparison", # I hate this rule (quoting @AbstractUmbra)
    "no-self-use",
    "non-empty-init-module", # we do some stuff here
    "suspicious-non-cryptographic-random-usage",
    "undefined-local-with-import-star",
    "undefined-local-with-import-star-usage",
]
extend-select = [
    # NumPy Doc convention turns these rules off
    "multi-line-summary-first-line", 
    "undocumented-param",
]
unfixable = [
    "commented-out-code",
    "unused-noqa",
]
flake8-quotes.inline-quotes = "double"

[tool.ruff.lint.per-file-ignores]
"{src/modules/beta.py,templates/fresh_beta.py,src/alpha.py,src/zeta.py,*.ipynb}" = [
    # These files are my playground to mess around and test stuff.
    "ANN",
    "D", 
    "missing-copyright-notice",
    "print",
    "unused-method-argument",
    "unused-noqa",
]
"src/modules/*.py" = [
    "undocumented-param", # I don't want to document all the `ctx: IreContext`
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint.isort]
split-on-trailing-comma = true
combine-as-imports = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"


[tool.pytest]
pythonpath = ["src"]
addopts = ["-vv", "-p", "no:cacheprovider", "--disable-warnings"]
norecursedirs = ["env/*", "venv/*", ".venv/*"]
filterwarnings = ["ignore::DeprecationWarning"]
testpaths = ["tests/"]
python_files = ["test_*.py"]
asyncio_mode = "auto"


[tool.esbonio.sphinx]
pythonCommand = ["uv", "run", "python"]
cwd = "/docs"
