name: Type, Lint, Test

on:
  push:
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize

jobs:
  type-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: "true"

      - name: Install uv
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d # v10.0.1
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync --dev

      - name: Basedpyright Type Checking
        run: uv run basedpyright

      # - name: Ty Type Checking (Choose one typechecker)
      #   run: uv run ty check src tests

      - name: Ruff Lint Checking
        run: uv run ruff check src tests examples --output-format github

      - name: Pytest Tests
        run: uv run pytest
        env:
          # it doesn't need any real .env values for most of it, just so pydantic doesn't crash out
          PROJECT_NAME: irenesbot
          TWITCH_CLIENT_ID: str
          TWITCH_CLIENT_SECRET: str
          TEST_TWITCH_CLIENT_ID: str
          TEST_TWITCH_CLIENT_SECRET: str
          POSTGRES_VPS: str
          POSTGRES_HOME: str
          STEAM_FRIEND_IRENE_ID64: 0
          STEAM_FRIEND_IRENE_ID32: 0
          STEAM_IRENESTEST_USERNAME: str
          STEAM_IRENESTEST_PASSWORD: str
          STEAM_IRENESBOT_USERNAME: str
          STEAM_IRENESBOT_PASSWORD: str
          STRATZ_BEARER: str
          STEAM_API_KEY: str
          SEVEN_TV_BEARER: ${{ secrets.SEVEN_TV_BEARER }}
          SPOTIFY_AIDENWALLIS: str
          EVENTSUB: str
          WEBHOOK_LOGGER: str
          WEBHOOK_ERROR: str
          WEBHOOK_HEARTBEAT: str
          WEBHOOK_STREAM_NOTIFS: str
